Option Strict Off
Option Explicit On
Imports Microsoft.VisualBasic
Imports System
Imports System.Windows.Forms
Imports System.Collections.Generic
<System.Runtime.InteropServices.ProgId("clsProcessCheck_NET.clsProcessCheck")> Public Class clsProcessCheck

  'OperatorID = 56982
  'END COMMON
  '
  'TestStep=1E
  'UUTType = CAM_0880_60P
  'OperatorID=
  'Barcode=02CT43000001
  'END PC

  ' **** Response
  'OperatorID = 56982
  'PCStatus = Fail
  'END COMMON
  '
  'CelesticaBarcode=98GA1A00001
  'AndrewBarcode=02CT43000001
  'PCStatus = Fail
  'PCString= Process check failed for FunctionTest. Go to VisualInspect.
  'UUTType=
  'OperatorID = 56982
  'END PC

  Public PC_IniFile As String

  Public PC_Check As Boolean
  Private RequestFile As String
  Private ResponseFile As String
  Private ProcessCheckEXE As String
  Private KillResponseFile As Boolean

  Private XferData As Boolean
  Private XferProg As String
  Public DataFile As String
  Private DCFDestinationPath As String
  Private DCFArchivePath As String
  Private DCFDeleteAfterTransfer As Boolean

  Public AssemblyType As String 'ULAM, MLAM', etc
  Public TestStep As String '1E, 2E, etc.

  Public OperatorID As String
  Public OverallStatus As Boolean

  Public Structure PC_Record
    Dim CelesticaBarcode As String
    Dim AndrewBarcode As String
    Dim Status As Boolean
    Dim ErrorMsg As String
    Dim UUTType As String
    Dim OperatorID As String
    Dim TestStep As String
    Dim Slot As String
  End Structure

  Public Function CheckOne(ByVal AndrewBarcode As String, ByRef CM_Barcode As String, ByRef ErrorMsg As String) As Boolean
    Dim recs(0) As PC_Record
    Dim PassStatus As Boolean
        
    recs(0).AndrewBarcode = AndrewBarcode
        recs(0).Slot = CStr(1)

        Call CheckMultiple(recs, PassStatus)
    CM_Barcode = recs(0).CelesticaBarcode
    ErrorMsg = recs(0).ErrorMsg
    CheckOne = PassStatus
  End Function

  Private Function CheckMultiple(ByRef recs() As PC_Record, ByRef PassStatus As Boolean) As Boolean
    Dim tmpb As Boolean
    Dim cmdline As String
    Dim i As Short

    If PC_IniFile = "" Then Call Err.Raise(vbObjectError + 1, "PC.CheckMultiple", "INI file not initialized")
    Call ReadIniFile()

    For i = LBound(recs) To UBound(recs)
      If recs(i).UUTType = "" Then recs(i).UUTType = AssemblyType
      If recs(i).TestStep = "" Then recs(i).TestStep = TestStep
    Next

    If PC_Check = False Then
      PassStatus = True
      Exit Function
    End If

    tmpb = WriteRequestFile(recs)
    If tmpb = False Then Exit Function

    cmdline = ProcessCheckEXE & " " & RequestFile & " " & ResponseFile
    Call Globals_Renamed.ExecCmd(cmdline)

    tmpb = ReadResponseFile(PassStatus, recs)
  End Function

  Public Function WriteRequestFile(ByRef recs() As PC_Record) As Boolean
    Dim fh, i As Short
    Dim Msg As String
    On Error GoTo ErrorHandler

    fh = FreeFile
    FileOpen(fh, RequestFile, OpenMode.Output)

    PrintLine(fh, "OperatorID=" & OperatorID)
    PrintLine(fh, "END COMMON")

    For i = LBound(recs) To UBound(recs)
      If recs(i).AndrewBarcode <> "" Then
        PrintLine(fh, "")
        Call WriteNextRecord(fh, recs(i))
      End If
    Next

    'Print #fh, "END PC"

    WriteRequestFile = True
    FileClose(fh)
    Exit Function
ErrorHandler:
    '*** If an error occurs, construct an error message
    '*** Check for error, then show message.
    If Err.Number <> 0 Then
      Msg = "Error # " & Str(Err.Number) & " was generated by " & Err.Source & Chr(13) & Err.Description & Chr(13) & "Press OK to Continue"
      MsgBox(Msg, , "Error")
      Err.Clear()
      FileClose(fh)
      WriteRequestFile = False
    End If

  End Function

  Private Sub WriteNextRecord(ByVal fh As Short, ByRef rec As PC_Record)
    'TestStep=1E
    'UUTType = CAM_0880_60P
    'OperatorID=
    'Barcode=02CT43000001
    'END PC
    PrintLine(fh, "TestStep=" & rec.TestStep)
    PrintLine(fh, "UUTType=" & rec.UUTType)
    PrintLine(fh, "OperatorID=" & rec.OperatorID)
    PrintLine(fh, "Barcode=" & rec.AndrewBarcode)
    PrintLine(fh, "Slot=" & rec.Slot)
    PrintLine(fh, "END PC")
  End Sub

  Public Function ReadResponseFile(ByRef PassStatus As Boolean, ByRef recs() As PC_Record) As Boolean
    Dim i, fh, NumRecs As Short
    Dim s As String
    Dim value, Key, Msg As String
    On Error GoTo ErrorHandler

    fh = FreeFile
    FileOpen(fh, ResponseFile, OpenMode.Input)

    Do Until EOF(fh)
      s = LineInput(fh)
      s = UCase(s)
      Select Case s
        Case "END COMMON"
          Exit Do
        Case Else
          i = InStr(1, s, "=") 'Find the number of the = sign
          If i > 0 Then
            Key = Trim(Left(s, i - 1)) 'key = Description
            value = Trim(Mid(s, i + 1)) 'grab everything to right 7 incl i
            Select Case Key
              Case "OPERATORID"
                OperatorID = value 'OperatorID is being passed back
              Case "PCSTATUS"
                PassStatus = CBool(value = "PASS")
            End Select
          End If
      End Select
    Loop

    'At this point we know If it has passed & if it has an operatorID
    'Now go get the rest of the stuff, ie.e barcode, slot etc...
    For i = LBound(recs) To UBound(recs)
      If recs(i).AndrewBarcode <> "" Then
        If Not ReadNextSection(fh, recs(i)) Then Exit For
      End If
    Next
    FileClose(fh)
    ReadResponseFile = True
    Exit Function
ErrorHandler:
    '*** If an error occurs, construct an error message
    '*** Check for error, then show message.
    If Err.Number <> 0 Then
      Msg = "Error # " & Str(Err.Number) & " was generated by " & Err.Source & Chr(13) & Err.Description & Chr(13) & "Press OK to Continue"
      MsgBox(Msg, , "Error")
      Err.Clear()
      FileClose(fh)
      ReadResponseFile = False
    End If

  End Function

  Private Function ReadNextSection(ByVal fh As Short, ByRef rec As PC_Record) As Boolean
    Dim Key, s, value As String
    Dim i As Short

    'CelesticaBarcode=98GA1A00001
    'AndrewBarcode=02CT43000001
    'PCStatus = Fail
    'PCString= Process check failed for FunctionTest. Go to VisualInspect.
    'UUTType=
    'OperatorID = 56982
    'END PC
    Do Until EOF(fh)
      s = LineInput(fh)
      s = UCase(Trim(s))

      Select Case s
        Case "END PC"
          ReadNextSection = True
          Exit Function
        Case Else
          i = InStr(1, s, "=")
          If i > 0 Then
            Key = Trim(Left(s, i - 1))
            value = Trim(Mid(s, i + 1))
            Select Case Key
              Case "CELESTICABARCODE"
                rec.CelesticaBarcode = value
              Case "ANDREWBARCODE"
                rec.AndrewBarcode = value
              Case "PCSTATUS"
                rec.Status = (value = "PASS")
              Case "PCSTRING"
                rec.ErrorMsg = value
              Case "UUTTYPE"
                rec.UUTType = value
              Case "OPERATORID"
                rec.OperatorID = value
            End Select
          End If
      End Select
    Loop
  End Function

  Private Sub ReadIniFile()
    'Process Check
    PC_Check = (UCase(ReadTestsetINI("ProcessCheck", "Enable", "FALSE")) = "TRUE")
    ProcessCheckEXE = ReadTestsetINI("ProcessCheck", "Program", "")
    If ProcessCheckEXE = "" Then PC_Check = False
    RequestFile = ReadTestsetINI("ProcessCheck", "RequestFile", "c:\PCRequest.txt")
    ResponseFile = ReadTestsetINI("ProcessCheck", "ResponseFile", "c:\PCResponse.txt")
    KillResponseFile = (UCase(ReadTestsetINI("ProcessCheck", "KillResponseFile", "TRUE")) = "TRUE")

    'Data Collection
    XferData = (UCase(ReadTestsetINI("DataCollection", "Enable", "FALSE")) = "TRUE")
    XferProg = ReadTestsetINI("DataCollection", "Program", "")
    If XferProg = "" Then XferData = False
    DataFile = ReadTestsetINI("DataCollection", "DataFile", "c:\testdata.dcf")
    DCFDestinationPath = ReadTestsetINI("DataCollection", "DCFDestinationPath", "None")
    DCFArchivePath = ReadTestsetINI("DataCollection", "DCFArchivePath", "None")
    DCFDeleteAfterTransfer = (UCase(ReadTestsetINI("DataCollection", "DCFDeleteAfterTransfer", "FALSE")) = "TRUE")
  End Sub
  Private Function ReadTestsetINI(ByVal App As String, ByVal Key As String, ByVal Def As String) As String
    ReadTestsetINI = Globals_Renamed.Read_INI_Field(App, Key, Def, PC_IniFile)
  End Function
  Public Sub TransferData()
    Dim dcfName As String
    Dim newDcfName As String
    Dim dcfPath As String
    Dim DCFDestTransferSuccessful As Boolean
    Dim DCFArcTransferSuccessful As Boolean

    If XferData Then
            Call Shell(XferProg & " " & DataFile, AppWinStyle.Hide, False, 500)
        End If

    If My.Computer.FileSystem.FileExists(DataFile) Then
      'The file name is assumed to end with ".dcf"
      dcfName = DataFile.Substring(DataFile.LastIndexOf("\"c) + 1)
      dcfPath = DataFile.Substring(0, DataFile.LastIndexOf("\"c))
      newDcfName = dcfName.Substring(0, dcfName.Length - 4) & "_" & Common.Testset_ID & "_" & Now.ToString("yyyyMMddhhmmss") & ".dcf"
      My.Computer.FileSystem.RenameFile(DataFile, newDcfName)
      If Not StrComp(DCFDestinationPath, "None", CompareMethod.Text) = 0 Then
        If StrComp(DCFDestinationPath.Substring(DCFDestinationPath.Length - 1), "\", CompareMethod.Binary) = 0 Then
          DCFDestinationPath = DCFDestinationPath.Substring(1)
        End If
        Try
          My.Computer.FileSystem.CopyFile(dcfPath & "\" & newDcfName, DCFDestinationPath & "\" & newDcfName)
          DCFDestTransferSuccessful = True
        Catch ex As Exception
          MsgBox("Error during file transfer." & vbCrLf & ex.ToString, MsgBoxStyle.Critical Or MsgBoxStyle.OkOnly, "File Transfer Error")
          DCFDestTransferSuccessful = False
        End Try
      End If
      If Not StrComp(DCFArchivePath, "None", CompareMethod.Text) = 0 Then
        If StrComp(DCFArchivePath.Substring(DCFArchivePath.Length - 1), "\", CompareMethod.Binary) = 0 Then
          DCFArchivePath = DCFArchivePath.Substring(1)
        End If
        Try
          My.Computer.FileSystem.CopyFile(dcfPath & "\" & newDcfName, DCFArchivePath & "\" & newDcfName)
          DCFArcTransferSuccessful = True
        Catch ex As Exception
          MsgBox("Error during file transfer." & vbCrLf & ex.ToString, MsgBoxStyle.Critical Or MsgBoxStyle.OkOnly, "File Transfer Error")
          DCFArcTransferSuccessful = False
        End Try
      End If

      If (DCFDestTransferSuccessful Or DCFArcTransferSuccessful) And DCFDeleteAfterTransfer Then
        My.Computer.FileSystem.DeleteFile(dcfPath & newDcfName)
      End If
    End If
  End Sub
End Class